// Code generated by protoc-gen-go.
// source: packet.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	Packet
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Packet struct {
	Serial           *int32  `protobuf:"varint,1,req,name=serial" json:"serial,omitempty"`
	Message          *string `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	SentTime         *int64  `protobuf:"varint,3,opt,name=sent_time" json:"sent_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Packet) GetSerial() int32 {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return 0
}

func (m *Packet) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Packet) GetSentTime() int64 {
	if m != nil && m.SentTime != nil {
		return *m.SentTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Packet)(nil), "main.Packet")
}

var fileDescriptor0 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xb2,
	0xe1, 0x62, 0x0b, 0x00, 0x8b, 0x0a, 0xf1, 0x71, 0xb1, 0x15, 0xa7, 0x16, 0x65, 0x26, 0xe6, 0x48,
	0x30, 0x2a, 0x30, 0x69, 0xb0, 0x0a, 0xf1, 0x73, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x4a, 0x30, 0x01, 0x05, 0x38, 0x85, 0x04, 0xb9, 0x38, 0x8b, 0x53, 0xf3, 0x4a, 0xe2, 0x4b, 0x32,
	0x73, 0x53, 0x25, 0x98, 0x15, 0x18, 0x35, 0x98, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0x1b,
	0x7e, 0x76, 0x52, 0x00, 0x00, 0x00,
}
